### ISSUE TITLE
Roulette Speed

### ISSUE THREAD

**Issue by nikitafloy** [IvanAdmaers/react-roulette-pro#1]
Hello. How can i setting roulette speed?

**Comment by IvanAdmaers** [comment]
Hello. It’s not possible to set the roulette speed now. But I think it’s a good idea. I’m going to implement it on the weekends. Thank you for your idea

**Comment by IvanAdmaers** [comment]
🎉 Released in [react-roulette-pro](https://www.npmjs.com/package/react-roulette-pro) 1.1.0  🎉

Take a look on the speed param. More in the README.

Thank you for your idea!
