### ISSUE TITLE
I would like to start rolling first for some time before get the prizeIndex.

### ISSUE THREAD

**Issue by ngdevc** [IvanAdmaers/react-roulette-pro#10]

**Comment by IvanAdmaers** [comment]
Hello. I'll think how to do it

**Comment by IvanAdmaers** [comment]
Take a look on this example [https://codesandbox.io/s/rrp-github-issue-10-y2y7op]( https://codesandbox.io/s/rrp-github-issue-10-y2y7op).

I use one `useEffect` to cancel spinning and another to start spinning again.

**Comment by ngdevc** [comment]
I can't see anything there.
I get the index through web socket, but before receive the socket event to get the index, I would like to begin the rolling for some secs first. Then If I receive the index through socket event, I would like to stop the rolling in the received index.

**Comment by IvanAdmaers** [comment]
Example: [https://codesandbox.io/s/rrp-github-issue-10-2-87492g](https://codesandbox.io/s/rrp-github-issue-10-2-87492g)

The idea is that first we start spinning to the end of the roulette because we need some time to wait for getting a `prizeIndex` from socket. When we got the `prizeIndex` from socket we change the `prizeIndex` useState value and the roulette automatically recalculate offset and continue spinning to the `prizeIndex` we got from socket.

**Comment by IvanAdmaers** [comment]
Sorry for the previous example link I wrote the code but forgot to save it)

**Comment by ngdevc** [comment]
It's not what I want.

**Comment by IvanAdmaers** [comment]
Do you want to stop the roulette after getting `prizeIndex` immediately?

**Comment by ngdevc** [comment]
No, it should be stop slowly.
But I would like to make rolling speed faster and rolling should be keep untill I get `prizeIndex `.
the speed should be like this.
https://user-images.githubusercontent.com/65579678/187271699-f91c41c3-4236-4223-831e-e3fc31ed3c58.mp4

**Comment by IvanAdmaers** [comment]
Ok. I’ll think about it.

**Comment by IvanAdmaers** [comment]
Is this implementation of infinity spinning ok for your goals - [https://codesandbox.io/s/friendly-mahavira-wq53mk](https://codesandbox.io/s/friendly-mahavira-wq53mk)?

**Comment by ngdevc** [comment]
It's too slow and If i start without prizeIndex, the rolling should be started with same speed.

**Comment by IvanAdmaers** [comment]
How about this speed - [https://codesandbox.io/s/friendly-mahavira-wq53mk?file=/src/App.js](https://codesandbox.io/s/friendly-mahavira-wq53mk)?

**Comment by IvanAdmaers** [comment]
Is this issue still actual?
