### ISSUE TITLE
Documentation to explain how it works

### ISSUE THREAD

**Issue by TimNZ** [IvanAdmaers/react-roulette-pro#11]
Thanks for creating this.

I wasted a bit of time trying to get this working the way and I expect everyone else expects.
Provide an array of things and it spins for a period of time landing on selected prize index.

It's not obvious at all that the spinner doesn't restart from the beginning i.e. an infinite loop,
instead you have to provide a big enough array to 'pad' out the spin long enough e.g. duplicating the items.

I couldn't understand why I was ending up with blank space at the end of the array items.

**Comment by IvanAdmaers** [comment]
Hi, @TimNZ. Thank you for your interest to this package.

You're absolutely right. Developer should provide a big enough array and there is an example how to implement it in README.

```js
const prizes = [{...}];

const reproductionArray = (array = [], length = 0) => [
  ...Array(length)
    .fill('_')
    .map(() => array[Math.floor(Math.random() * array.length)]),
];

const reproducedPrizeList = [
  ...prizes,
  ...reproductionArray(prizes, prizes.length * 3),
  ...prizes,
  ...reproductionArray(prizes, prizes.length),
];
```

Do you think it'd be better to add some more information about it in the README?

**Comment by TimNZ** [comment]
Hey @IvanAdmaers.

Definitely need to document how this works instead of someone seeing this code and doing the mental gymnastics to figure out what I eventually figured out.

If you had a paragraph explaining the mechanics e.g. using CSS animation to transform, it doesn't loop you have to pad, then you might have also eliminated a couple of other issue questions around controlling spin time and spinning endlessly until told to start.

**Comment by IvanAdmaers** [comment]
Ok. Thank you very much for your feedback. I'll add a section where be details about how does this roulette work.

If you'll have any other ideas feel free to share it.

**Comment by TimNZ** [comment]
Good stuff, thanks.

**Comment by maiconcarraro** [comment]
@IvanAdmaers first of all, congratulations for the hard work.

I was looking how to customize the width, found some old comments w/ advanced examples that had a prop for the width... and now they don't exist ([ref](https://github.com/IvanAdmaers/react-roulette-pro/issues/4#issuecomment-1025399475)), what happened? and how to do?

And 👍 about having to do "mental gymnastics", solving this it will be the best react solution for roulette.

**Comment by IvanAdmaers** [comment]
Hi, @maiconcarraro. Thank you for interest to this package! There is a few words about styling in the [FAQ](https://github.com/IvanAdmaers/react-roulette-pro#faq) section.

"🧐 How can I customize the roulette?
📣 First, you can pass a prizeItemRenderFunction to render prize items by yourself. Second, you can use a specific design plugin. Third, you can pass your specific classes via classes prop. Avoid to rewrite the roulette and its plugins default styles".

For example, you can add your own class name that will specify width and height via the `classes` prop.

```jsx
<RoulettePro
classes={{ prizeItem: 'my-own-class' }}
/>
```

Is this what are you looking for?

**Comment by maiconcarraro** [comment]
> Hi, @maiconcarraro. Thank you for interest to this package! There is a few words about styling in the [FAQ](https://github.com/IvanAdmaers/react-roulette-pro#faq) section.
> 
> "🧐 How can I customize the roulette? 📣 First, you can pass a prizeItemRenderFunction to render prize items by yourself. Second, you can use a specific design plugin. Third, you can pass your specific classes via classes prop. Avoid to rewrite the roulette and its plugins default styles".
> 
> For example, you can add your own class name that will specify width and height via the `classes` prop.
> 
> ```js
> <RoulettePro
> classes={{ prizeItem: 'my-own-class' }}
> />
> ```
> 
> Is this what are you looking for?

I used the `prizeItemRenderFunction`, but if the height/width is different from the expected, it causes a mismatch for the selected winner. It only worked using the magic numbers from your Regular.tsx
```js
    const prizeItemHeightWithoutText = type === 'vertical' ? 172 : 174;
    const prizeItemHeight: number =
      prizesWithText === true ? 234 : prizeItemHeightWithoutText;
```

For now it is good, was just curious about what happened between the versions.

**Comment by IvanAdmaers** [comment]
It's because in React Roulette Pro 3.0 was added design plugins architecture and now the roulette gets prize items width and height from a design plugin. In RRP 2.0 width and height was set by the roulette so that's why there is changed API for setting prize items width and height.

**Comment by IvanAdmaers** [comment]
It's always better to do it late than not to do it at all, right? Improved the doc in 3.0.9. Thank you for your suggestion. Feel free to open a new issue if you have any other suggestions.
