### ISSUE TITLE
repeat sound while Spin works

### ISSUE THREAD

**Issue by RicardoCassio** [IvanAdmaers/react-roulette-pro#13]
I have a sound that I want to be repeated every time the spin passes over an image/Item.

It is possible?

**Comment by IvanAdmaers** [comment]
Hello, @RicardoCassio. Thank you for your interest in this package.

Unfortunately it's not possible at this moment. Now you can only start a sound that will play static while the roulette spinning.

**Comment by IvanAdmaers** [comment]
If you'll have another question feel free to open a new issue.
