### ISSUE TITLE
How to keep on spinning until the API fetches the name and get the prizeIndex based off of that?

### ISSUE THREAD

**Issue by wendoj** [IvanAdmaers/react-roulette-pro#14]
So I want to make it so that when the user presses the "Open Case" button, it sends a POST request to the API and sets the prizeIndex based off the name that the API will return and keep on spinning while retrieving the data.

```js
const [start, setStart] = useState(false);
const [prizeIndex, setPrizeIndex] = useState(0);
const prizes = items.map((item) => {
  return {
    image: item.image,
    text: item.name,
    value: item.value,
    chance: item.chance.toFixed(3),
  };
});

const reproductionArray = (array = [], length = 0) => [
  ...Array(length)
    .fill("_")
    .map(() => array[Math.floor(Math.random() * array.length)]),
];

const reproducedPrizeList = [
  ...prizes,
  ...reproductionArray(prizes, prizes.length * 3),
  ...prizes,
  ...reproductionArray(prizes, prizes.length * 40),
];

const prizeList = reproducedPrizeList.map((prize) => ({ ...prize }));

function handleStart() {
  setPrizeIndex(prizeList.length - 10);
}

useEffect(() => {
  if (prizeIndex === 0) return;

  setStart(true);
}, [prizeIndex]);

useEffect(() => {
  if (!start) return;

  axios
    .post("/api/case", { cookie: user.cookie, continentCode, name })
    .then((res) => {
      const prizeName = res.data.prize.name;
      const prizeIndex = prizeList.findIndex(
        (prize) => prize.text === prizeName
      );
      setPrizeIndex(prizeIndex);
      setStart(true);
    })
}, [start]);
```
```jsx
<RoulettePro
    spinningTime={20}
    prizes={prizeList}
    prizeIndex={prizeIndex}
    start={start}
    options={{
      withoutAnimation: true,
      stopInCenter: false,
    }}
    onPrizeDefined={() => handlePrizeDefined()}
    defaultDesignOptions={{ prizesWithText: true }}
/>
```

**Comment by IvanAdmaers** [comment]
Hello, @wendoj. Thank you for your interest in this package.

I’ll try to create an example of how to implement this on the weekends.

**Comment by IvanAdmaers** [comment]
There is a similar issue - [https://github.com/IvanAdmaers/react-roulette-pro/issues/10](https://github.com/IvanAdmaers/react-roulette-pro/issues/10). There I placed some code examples. I think this code example - [https://codesandbox.io/s/rrp-github-issue-10-2-87492g](https://codesandbox.io/s/rrp-github-issue-10-2-87492g) might be helpful for your case.

**Comment by wendoj** [comment]
I sometimes experience a problem where it either lands on the last one despite the index changing, or it also spins backwards. Is there a way to solve this?

[https://i.gyazo.com/5c74d846795b3bbd47ddd8ab77bc0b1b.mp4](https://i.gyazo.com/5c74d846795b3bbd47ddd8ab77bc0b1b.mp4)
[https://i.gyazo.com/d6f90e62a029df9c6f28f1ef59336d91.mp4](https://i.gyazo.com/d6f90e62a029df9c6f28f1ef59336d91.mp4)

Here is an implementation of the code I was using in the videos above:
[https://codesandbox.io/s/rrp-github-issue-10-2-forked-bev9dv?file=/src/App.js](https://codesandbox.io/s/rrp-github-issue-10-2-forked-bev9dv?file=/src/App.js)

**Comment by IvanAdmaers** [comment]
1. How to prevent it from sometimes spinning directly to the last prize:
It happens because we get a prize index when the roulette have already spun this prize item. Solution: when we get a prize index we need to start spinning again.

2. Prevent it from spinning back to the start when setting it:
It happens because the roulette have already spun that prize item.

I also fixed getting a prize index in that example.

Please, check the updated example: [https://codesandbox.io/s/spinning-before-getting-prizeindex-react-roulette-pro-issue-14-ewwszg?file=/src/App.js](https://codesandbox.io/s/spinning-before-getting-prizeindex-react-roulette-pro-issue-14-ewwszg?file=/src/App.js)

Let me know if something is wrong.

**Comment by wendoj** [comment]
Thank you for your help - it works now :)

**Comment by IvanAdmaers** [comment]
You're always welcome! Feel free to open a new issue anytime.
