### ISSUE TITLE
fanart

### ISSUE THREAD

**Issue by lxnnydev** [IvanAdmaers/react-roulette-pro#16]
ivan fanart
![image](https://user-images.githubusercontent.com/89148963/198621511-33221b64-c12b-4c55-afe7-e80dcf909e35.png)
good?

**Comment by IvanAdmaers** [comment]
I’ve printed this out and hung it in my room

**Comment by lxnnydev** [comment]
![bXVjZCJg_male_4_cartoon1](https://user-images.githubusercontent.com/89148963/198690246-78826841-0e42-4867-8d14-8e6a76e6c4ac.png)
batman ivan

**Comment by IvanAdmaers** [comment]
Cool
