### ISSUE TITLE
Spinning Speed is different

### ISSUE THREAD

**Issue by lxnnydev** [IvanAdmaers/react-roulette-pro#20]
Hi! Depending on how many items are in the component, the spinning times are different. Is there any way to fix that?

**Comment by IvanAdmaers** [comment]
Hi. You can you the spinningTime prop. On 4 Feb 2023, at 9:48 a.m., lxnny ***@***.***> wrote:﻿
Hi! Depending on how many items are in the component, the spinning times are different. Is there any way to fix that?

**Comment by lxnnydev** [comment]
Can you give me an example? its kind of confusing tbh

**Comment by IvanAdmaers** [comment]
```jsx
<RoulettePro spinningTime={20} />
```

**Comment by lxnnydev** [comment]
but that doesnt change the speed

**Comment by lxnnydev** [comment]
To specify want I want. I want multiple roulettes with a different amount of items but with the same spinning speed and time.

**Comment by IvanAdmaers** [comment]
I understood what you want. I think it may be implemented by using the `spinningTime` prop. But now it seems like this prop works incorrect. I need to check why does this happen and then I'll let you know.

**Comment by IvanAdmaers** [comment]
UPD: the `spinningTime` prop works well. I just forgot to save the file

**Comment by IvanAdmaers** [comment]
I set the `spinningTime` prop and two roulettes on the page stopping at the same time - [example](https://codesandbox.io/s/react-roulette-pro-multiple-roulettes-with-a-different-amount-of-items-but-with-the-same-spinning-speed-and-time-issue-20-2xk1x2?file=/src/App.js). Is this what are you looking for?

**Comment by lxnnydev** [comment]
Nope, The top one is way slower than the bottom one. I want both being the same speed. Thank you for your current help though

**Comment by IvanAdmaers** [comment]
I think it's not possible to have multiple roulettes with a different amount of items but with the same spinning speed and time. To implement both of your conditions you gotta set the same `prizes` length to both of your roulettes.

**Comment by lxnnydev** [comment]
Hmm, Sad, Thank you for your help though.

**Comment by IvanAdmaers** [comment]
No problem. Feel free to open a new issue if you have any questions. Have a good one.
