### ISSUE TITLE
Center Item after winning

### ISSUE THREAD

**Issue by mance819** [IvanAdmaers/react-roulette-pro#23]
Is there a way to center the item  after the spin is finished?

**Comment by IvanAdmaers** [comment]
Hello. Yes. You can use the _options_ prop.

options: { stopInCenter: true } 

Playground - https://react-roulette-pro.ivanadmaers.com/

**Comment by mance819** [comment]
I meant  that it stops anywhere on the item and after it stops it goes to the center. But you gave me an idea, ill set the {stopinCenter :true} after the prize ahs been defined

**Comment by IvanAdmaers** [comment]
Unfortunately there is no implementation for centring after the roulette stop spinning at this moment. I’ll think about how to implement this. Thank you for your idea.On 21 Feb 2023, at 9:06 a.m., mance819 ***@***.***> wrote:﻿
I meant  that it stops anywhere on the item and after it stops it goes to the center. But you gave me an idea, ill set the {stopinCenter :true} after the prize ahs been defined

**Comment by mance819** [comment]
I tried something on your  example page. after you spin an item and then activate "Stop in the prize item center" it will center the item but the speed will depend on the spinning speed. So if speed is 3 it will be very fast and if speed is 20 it will be slow.

**Comment by IvanAdmaers** [comment]
Thank you. I’ll take a look on it tomorrow.

**Comment by IvanAdmaers** [comment]
Good quote. There is a need to think about it. Thank you.
