### ISSUE TITLE
prizeItemRenderFunction breaks winning index

### ISSUE THREAD

**Issue by Michael24566** [IvanAdmaers/react-roulette-pro#29]
I wanted to change the width of roulette-pro-regular-prize-item which is default 205px. I ended up using the prizeItemRenderFunction to accomplish this, but now the prizeIndex doesn't line up how I would expect anymore. Is it impossible to change the width of each item, or did I do it incorrectly/miss a feature of prizeItemRenderFunction.

Here is an example of my prizeItemRenderFunction:
![image](https://github.com/IvanAdmaers/react-roulette-pro/assets/56282412/8f45e363-8c57-4055-bb34-b94bc0bcab82)

roulette implementation:
![image](https://github.com/IvanAdmaers/react-roulette-pro/assets/56282412/89820f05-cc2f-464e-a2b1-bbf464756d10)

**Comment by IvanAdmaers** [comment]
Hi, @Michael24566! Thank you so much for this issue.

At this moment the roulette defines its items width from a design plugin. So when you change width in `prizeItemRenderFunction` it will work incorrect. Of course this must be fixed and I will do this when I have time.

For now I can suggest you this solution:

Keep your prize items render function.
Add a prop `designPlugin` and specify your items width and height there like this:
```js
<RoulettePro
...
     designPlugin={() => ({
          prizeItemWidth: 100,
          prizeItemHeight: 100,
      })}
...
/>
```

It should works. If it's not, please let me know.

**Comment by IvanAdmaers** [comment]
TODO:

To fix the case when the roulette items width and height or one of them is changing in the `prizeItemRenderFunction`. 

Issue: Currently the roulette defines its items width and height from a design plugin.

**Comment by Michael24566** [comment]
This seems to have fixed my original issue, thank you @IvanAdmaers. After applying the designPlugin it seems to have made the center delimiter disappear. Is there a property I can pass designPlugin to keep the delimiter? 

Thanks again I'll mark this as closed soon since the original issue has been fixed.

**Comment by IvanAdmaers** [comment]
I do apologize for this confusion. Please, add the `topChildren` key to the `designPlugin` returning options.

```js
      <RoulettePro
...
        designPlugin={() => ({
          prizeItemWidth: 100,
          prizeItemHeight: 100,
          topChildren: (
            <div
              className="roulette-pro-regular-design-top horizontal"
            />
          )
        })}
      />
```

**Comment by Michael24566** [comment]
That did the trick, this was exactly what I was looking for. Thank you again @IvanAdmaers.

**Comment by IvanAdmaers** [comment]
@Michael24566, I’m glad I could help you with this issue. Feel free to open a new one anytime. And I’ll fix the prize items width and height definition problem as soon as I have time.

Have a great week!

**Comment by IvanAdmaers** [comment]
To whom it may concern.

At this moment, the solution described here is up to date. More details - https://github.com/IvanAdmaers/react-roulette-pro/issues/30#issuecomment-1567291557
