### ISSUE TITLE
Support for custom roulette elements

### ISSUE THREAD

**Issue by pahas** [IvanAdmaers/react-roulette-pro#3]
Hi. I'd really like to see support for custom roulette spinning elements. Overall the package is great and many thanks for it, but I'm really missing this feature, if you don't have plans on implementing this I guess I'll have to modify it myself :(

**Comment by IvanAdmaers** [comment]
Hello, @pahas! Thank you for your interest in this package.

I have an idea to make a custom render function for the roulette elements.
It'll look something like this:
```jsx
<RoulettePro
renderFunction={({ id, image, text }) => (
  <div key={id}>
    {/* Your custom element here */}
  </div>
)}
/>
```

I'll implement it soon. Approximately on the weekend.

Thank you for your support.

**Comment by IvanAdmaers** [comment]
And by the way. You can modify this package whatever you want because it is under the MIT license.

**Comment by IvanAdmaers** [comment]
🥳 React Roulette Pro 1.3.0 is released 🥳

New props:
`prizeRenderFunction` - a function that renders your roulette prize items. Customize your prize items as you need.
`prizeWidth` - a prize width in px.

Examples are in the [AdvancedUsage.js](https://github.com/IvanAdmaers/react-roulette-pro/blob/main/example/src/AdvancedUsage.js)

I hope it'll help you. If I can make something else just let me know.

Thank you for your support. I really appreciate it!

**Comment by pahas** [comment]
Thanks, I have been playing myself with this package for some time and almost got what I needed. BTW I meant more raw solution for prizes, because I use my own React element for the prize cards, the API doesn't kinda suit me, but I made some modifications for myself so it's ok, I guess this is not a common usage.

Also, would you ever be interested in implementing something like current center element highlighting or when the roulette ends, make the card bigger. I'll attach an example design so you can understand. (the center gray card)
![image](https://user-images.githubusercontent.com/28705820/150997039-09a5335b-1d09-4543-88ea-89cac4ed7e4a.png)

**Comment by IvanAdmaers** [comment]
Your idea looks interesting. I’ll play with it tomorrow and let you know. Thank you!

**Comment by IvanAdmaers** [comment]
About something like current center element highlighting.

You can highlighting the center element by using `box-shadow`.

<img width="883" alt="screen" src="https://user-images.githubusercontent.com/66776981/151125294-3858c004-e818-4696-9107-140e9c0da1b6.png">

About make the card bigger when the roulette ends.

It's possible to make it with useRef. We can add a ref to the prize item that should win and when the roulette stop spinning add some styles like transform scale. I've added your idea to my implement list it but It won't be implemented soon because it requires architecture change and I'll do it when I have enough time.

If you have any more ideas or questions just write them. I'll try to help!

**Comment by pahas** [comment]
Okay, but do you have any idea how to keep center element highlighted? I guess that's what requires arch changes?

**Comment by IvanAdmaers** [comment]
To keep center element highlighted when the roulette spinning you should add something like this:

```css
.roulette-pro-prizes-container::after {
  content: "";
  width: 200px;
  height: 234px;
  background-color: transparent;
  position: absolute;
  z-index: 999;
  top: 0;
  bottom: 0;
  left: 50%;
  transform: translateX(calc(-50% + 4px));
  margin: auto;
  /* box-shadow: 0 0 50px 20px royalblue; */
  border: 3px solid royalblue;
  overflow: hidden;
}
```
<img width="1069" alt="s2" src="https://user-images.githubusercontent.com/66776981/151300946-89abdf73-6c0d-4cc4-b092-d2b62b30203b.png">

But when the roulette stop spinning this border is still active.

<img width="1070" alt="s1" src="https://user-images.githubusercontent.com/66776981/151300887-38afe013-ce98-4320-ba6d-b5ce85dc014f.png">

How to fix:

```javascript
// Outside the component
const css = document.createElement('style');
css.textContent = `
.roulette-pro-prizes-container::after {
  content: "";
  width: 200px;
  height: 234px;
  background-color: transparent;
  position: absolute;
  z-index: 999;
  top: 0;
  bottom: 0;
  left: 50%;
  transform: translateX(calc(-50% + 4px));
  margin: auto;
  border: 3px solid royalblue;
  overflow: hidden;
}
`;

// Inside the component
const [showBorder, setShowBorder] = useState(true);

  const handlePrizeDefined = useCallback(() => {
    console.log('🥳 Prize defined! 🥳');

    setShowBorder(false);
  }, []);

  useEffect(() => {
    if (!showBorder) {
      return document.head.lastElementChild.remove();
    }

    document.head.appendChild(css);
  }, [showBorder]);
```

---

If you want to highlight the element after the roulette stop spinning:

```javascript
// Inside the component
const [highlight, setHighlight] = useState(false);

  const handlePrizeDefined = useCallback(() => {
    console.log('🥳 Prize defined! 🥳');

    setHighlight(true);
  }, []);


  useEffect(() => {
    if (!highlight) {
      return;
    }

    const element = document.querySelector(
      `.roulette-pro-prize-item:nth-child(${prizeIndex + 1})`,
    );

    const currentStyle = element.getAttribute('style');
    element.style = `
      ${currentStyle}
      position: relative;
      z-index: 999;
      box-shadow: 0 0 50px 20px royalblue;
    `;
  }, [highlight, prizeIndex]);
```

Is this what you are looking for?

**Comment by pahas** [comment]
Initially I thought about something like when the roulette is spinning, element which shows up in center should be bigger for few milliseconds, but now I guess generally this isn't a good practice and my design has changed. Thanks anyways for efforts! I'll close the issue now
