### ISSUE TITLE
Indicator on the middle of two results

### ISSUE THREAD

**Issue by AlvaroFalcon** [IvanAdmaers/react-roulette-pro#38]
Hey, awesome library but im having one issue:

I have a TopChildren with the following css:

`.arrow {
  z-index: 10;
  width: 0;
  height: 0;
  border-left: 70px solid transparent;
  border-right: 70px solid transparent;
  border-top: 70px solid white;
  position: relative;
  top: -1rem;
  margin: auto;
}
`

but it does not always point to a result, sometimes it points in the middle, any clue of why this might be happening?

**Comment by IvanAdmaers** [comment]
Hi, Alvaro. If you need this roulette to be stopped in the center of item, then pass the prop ‘options={{ stopInCenter: true }}’. Or you’re looking for something else?On 5 Aug 2024, at 10:12 p.m., Alvaro Eduardo Falcón Morales ***@***.***> wrote:﻿
Hey, awesome library but im having one issue:
I have a TopChildren with the following css:
.arrow { z-index: 10; width: 0; height: 0; border-left: 70px solid transparent; border-right: 70px solid transparent; border-top: 70px solid white; position: relative; top: -1rem; margin: auto; } 
but it does not always point to a result, sometimes it points in the middle, any clue of why this might be happening?

**Comment by AlvaroFalcon** [comment]
I think that might work! will try it out, thank you very much.

Will reply whenever I have the time to test it if it works, thanks

**Comment by AlvaroFalcon** [comment]
I've got a roulette with game images, after adding that option this issue is still happening, may I be doing something wrong?

<img width="736" alt="imagen" src="https://github.com/user-attachments/assets/ea41783b-bc1b-45d3-8f6f-74e550215366">


here is an example.

I've noted that resizing the windows the position changes, might it be related to width?

**Comment by IvanAdmaers** [comment]
It looks like you’ve changed padding between items or items width. The roulette calculating offset based on items width. If items width or padding between them had been change the roulette calculating offset incorrect. To fix it, you need to use design plugin. The prop called: ‘designPlugin‘ (see README.md). Example: https://github.com/IvanAdmaers/react-roulette-pro/blob/main/src/designs/Regular/Regular.tsx.By using this, you’ll let the roulette know your items width and height, so it can calculate its offset right.On 6 Aug 2024, at 6:42 PM, Alvaro Eduardo Falcón Morales ***@***.***> wrote:﻿
I've got a roulette with game images, after adding that option this issue is still happening, may I be doing something wrong?
imagen.png (view on web)
here is an example

**Comment by IvanAdmaers** [comment]
If you won’t be able to fix it, send me a link to codesandboxOn 6 Aug 2024, at 6:42 PM, Alvaro Eduardo Falcón Morales ***@***.***> wrote:﻿
I've got a roulette with game images, after adding that option this issue is still happening, may I be doing something wrong?
imagen.png (view on web)
here is an example

**Comment by AlvaroFalcon** [comment]
Sorry missed the message.

Thank you for your reply, the thing is that I already have my custom design:

```
import React from 'react';
import {IDesignPlugin} from "react-roulette-pro";
import {EmptyGameIcon} from "../resources/Icons";


const TopChildren = () => {
  return (
    <div
      className={`arrow`}
    />
  );
};

const PrizeItem = ({ image, text }: { image: string, text: string | undefined }) => {
  return (
    <div className={'roulette-pro-regular-prize-item-wrapper center'}>
      <div className="roulette-pro-regular-image-wrapper">
        <img src={image} alt={text || "Game"} className="roulette-pro-regular-prize-item-image"/>
      </div>
    </div>
  );
}

const EmptyPrizeItem = () => {
  return (
    <div>
      <EmptyGameIcon/>
    </div>
  );

}

const gameDesign = () => (): IDesignPlugin => {
      const prizeItemWidth: number = 120;
      const prizeItemHeight: number = 160;

      return {
        topChildren: (
          <TopChildren/>
        ),
        bottomChildren:null,
        prizeItemWidth,
        prizeItemHeight,
        prizeItemRenderFunction: ({ image, text }) => {
          return (
            <>
              {image === "" ? <EmptyPrizeItem/> : <PrizeItem image={image} text={text}/>}
            </>
          );
        },
      };
    };

export default gameDesign;
```
Will try to fix it, otherwise I'll be attaching a codesandbox as you mentioned, thank you

edit: 

forgot that I've added this CSS

```
.roulette-pro-prize-list {
  gap: 1rem !important;
}
```

**Comment by IvanAdmaers** [comment]
Try to remove the `.roulette-pro-prize-list` class. If the roulette will stop correct, this means you need to change your `const prizeItemWidth: number = 120`. Let me known after you try it

**Comment by IvanAdmaers** [comment]
No problem. Just keep in mind that prizeItemWidth needs to be correct and include all paddings. For example, item width is 100px. And it has padding-x: 20px. Total width is: 100 + 20 * 2 = 140px. Feel free to contact me here if you need any helpOn 8 Aug 2024, at 12:56 a.m., Alvaro Eduardo Falcón Morales ***@***.***> wrote:﻿
Sorry missed the message.
Thank you for your reply, the thing is that I already have my custom design:
import React from 'react';
import {IDesignPlugin} from "react-roulette-pro";
import {EmptyGameIcon} from "../resources/Icons";


const TopChildren = () => {
  return (
    <div
      className={`arrow`}
    />
  );
};

const PrizeItem = ({ image, text }: { image: string, text: string | undefined }) => {
  return (
    <div className={'roulette-pro-regular-prize-item-wrapper center'}>
      <div className="roulette-pro-regular-image-wrapper">
        <img src={image} alt={text || "Game"} className="roulette-pro-regular-prize-item-image"/>
      </div>
    </div>
  );
}

const EmptyPrizeItem = () => {
  return (
    <div>
      <EmptyGameIcon/>
    </div>
  );

}

const gameDesign = () => (): IDesignPlugin => {
      const prizeItemWidth: number = 120;
      const prizeItemHeight: number = 160;

      return {
        topChildren: (
          <TopChildren/>
        ),
        bottomChildren:null,
        prizeItemWidth,
        prizeItemHeight,
        prizeItemRenderFunction: ({ image, text }) => {
          return (
            <>
              {image === "" ? <EmptyPrizeItem/> : <PrizeItem image={image} text={text}/>}
            </>
          );
        },
      };
    };

export default gameDesign;

Will try to fix it, otherwise I'll be attaching a codesandbox as you mentioned, thank you

**Comment by AlvaroFalcon** [comment]
Sorry missed this, will try over the weekend and let you know, thanks for the help.

**Comment by AlvaroFalcon** [comment]
Didn't have much time sorry, but I've tried removing the CSS class and changed the width to 120 as mentioned and im getting this:
<img width="824" alt="imagen" src="https://github.com/user-attachments/assets/f1e8b2d5-1ed9-452a-a5f7-60e08050713f">

here is my code:

```
import React from 'react';
import {IDesignPlugin} from "react-roulette-pro";
import {EmptyGameIcon} from "../resources/Icons";


const TopChildren = () => {
  return (
    <div
      className={`arrow`}
    />
  );
};

const PrizeItem = ({ image, text }: { image: string, text: string | undefined }) => {
  return (
    <div className={'roulette-pro-regular-prize-item-wrapper center'}>
      <div className="roulette-pro-regular-image-wrapper">
        <img src={image} alt={text || "Game"} className="roulette-pro-regular-prize-item-image"/>
      </div>
    </div>
  );
}

const EmptyPrizeItem = () => {
  return (
    <div>
      <EmptyGameIcon/>
    </div>
  );

}

const gameDesign = () => (): IDesignPlugin => {
      const prizeItemWidth: number = 120;
      const prizeItemHeight: number = 160;

      return {
        topChildren: (
          <TopChildren/>
        ),
        bottomChildren:null,
        prizeItemWidth,
        prizeItemHeight,
        prizeItemRenderFunction: ({ image, text }) => {
          return (
            <>
              {image === "" ? <EmptyPrizeItem/> : <PrizeItem image={image} text={text}/>}
            </>
          );
        },
      };
    };

export default gameDesign;

```

spacing from inspector

<img width="1589" alt="imagen" src="https://github.com/user-attachments/assets/27b2243b-4910-4199-b546-ee52f09311fd">


Thank you for the support

**Comment by IvanAdmaers** [comment]
Hi, @AlvaroFalcon. Could you provide your `RoulettePro` props? I mean:

```jsx
      <RoulettePro
        prizes={prizeList}
        prizeIndex={prizeIndex}
        start={start}
       ...etc
      />
```

**Comment by AlvaroFalcon** [comment]
```
        <Roulette prizes={formedPrizeList.length > 0 ? formedPrizeList : formedEmptyList}
                  prizeIndex={prizeIndex} start={start}
                  onPrizeDefined={handlePrizeDefined}
                  options={{stopInCenter: true}}
                  designPlugin={gameDesign()}
        />
```

There you go, thanks

**Comment by IvanAdmaers** [comment]
<img width="1573" alt="screen" src="https://github.com/user-attachments/assets/c49c231c-5021-41ae-8186-c3c4279d1dfe">

Try to add these styles and let me know if anything changes

**Comment by IvanAdmaers** [comment]
Also, if the roulette stops after its items (like [here](https://private-user-images.githubusercontent.com/5773336/365643879-27b2243b-4910-4199-b546-ee52f09311fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMDY2NjQsIm5iZiI6MTcyNjIwNjM2NCwicGF0aCI6Ii81NzczMzM2LzM2NTY0Mzg3OS0yN2IyMjQzYi00OTEwLTQxOTktYjU0Ni1lZTUyZjA5MzExZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDU0NjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBhODQxOThmZTdkNTMxMDA5YThjZGExMDE0YWUzOTU4NWMwMWNlZjJkODM1YmM1OTc5MDJkMjE4YjRhMjI2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9uh5UR7cl9mYwXq0erYySdANxYtAQ8sB0LqiVqgUlVQ)), then you should check your `prizeIndex`

**Comment by AlvaroFalcon** [comment]
still happening this 
<img width="1050" alt="imagen" src="https://github.com/user-attachments/assets/a83194e4-947e-43e5-b02a-13f652fec8fe">

code to generate the list of item prizes, just in case

```
const getFormedPrizeList = (prizeList: PrizeType[]) => {
  const reproductionArray = (array: PrizeType[] = [], length = 0) => [
    ...Array(length)
      .fill('_')
      .map(() => array[Math.floor(Math.random() * array.length)]),
  ];
  return [
    ...prizeList,
    ...reproductionArray(prizeList, prizeList.length * 3),
    ...prizeList,
    ...reproductionArray(prizeList, prizeList.length),
  ].map((prize, index) => ({...prize, id: index}));
}

const emptyPrizeArray: PrizeType[] = Array(20).fill({id: 1, image: "" }, 0, 20).map((_, index) => ({id: index, image: ""}));

```

**Comment by IvanAdmaers** [comment]
When this happens, how many items in the `prizes` array do you have and what is the value of `prizeIndex`?

**Comment by AlvaroFalcon** [comment]
Will check this during the weekend, sorry, didnt have much time

**Comment by IvanAdmaers** [comment]
It’s ok. No problem On 20 Sep 2024, at 7:53 PM, Alvaro Eduardo Falcón Morales ***@***.***> wrote:﻿
Will check this during the weekend, sorry, didnt have much time

**Comment by AlvaroFalcon** [comment]
sorry, debugging this, this is how it is:

<img width="1727" alt="imagen" src="https://github.com/user-attachments/assets/c30388ec-5ce4-482a-a73d-0e4109131d9f">

edit:

I think that the issue is this:
`const prizeIndex = formedPrizeList.length;`

prizeIndex basically indicates the prize and rotates the roulete until hit, right? then I made a big mistake...

**Comment by IvanAdmaers** [comment]
@AlvaroFalcon You're right about the `prizeIndex`. It should be less than the total length of `formedPrizeList`

**Comment by AlvaroFalcon** [comment]
thank you, I think I can close this finally as this is working! thanks for the support

**Comment by IvanAdmaers** [comment]
You're welcome, @AlvaroFalcon. Feel free to open a new issue if you have any questions
