### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by leineveber** [IvanAdmaers/react-roulette-pro#5]
Maybe, it will be a good idea to add sounds to roulette?

**Comment by IvanAdmaers** [comment]
Hello, @leineveber. Thank you for your ideas. It’s ease to use a sound effect after the roulette stop spinning using ‘onPrizeDefined’.
I’ll think how to implement a sound effect while spinning. I’ll let you know here.

**Comment by IvanAdmaers** [comment]
Hello, @leineveber. I’m going to implement a sound playing while the roulette spinning when I have free time. But it won’t be a sound when a roulette item crosses the center roulette seporator by performans reasons. It’ll be a static sound while the roulette spinning. Thank you for your idea!

**Comment by IvanAdmaers** [comment]
🎉 Implemented in React Roulette Pro 2.1 🎉

The roulette now supports the `soundWhileSpinning` prop.
Available in the live example - [https://react-roulette-pro.ivanadmaers.com/](https://react-roulette-pro.ivanadmaers.com)

If you have any more ideas or questions, feel free to open a new issue.
