### ISSUE TITLE
When Roulette renders, keep the "pointer" over specific index

### ISSUE THREAD

**Issue by kasteckis** [IvanAdmaers/react-roulette-pro#6]
Hello, I'm running a default script from README.md.

Current behaviour: When I load up page, prize winner "pointer" is slowly spinning towards the right side.

Wanted behaviour: When I load up page, I want that prize winner "pointer" would be locked in on my specific index (for example Macbook Pro).

Is it possible to achieve that?

**Comment by IvanAdmaers** [comment]
Hello, @kasteckis.

First, you should disable auto spinning via providing this prop:
```
<RoulettePro
...
designOptions={{ withoutAnimation: true }}
...
/>
```

Then you should make to your wanted prize item will be in the center of the roulette. Make sure its prize item has the array index which makes it in the center. For example if the roulette has width 1200px your wanted prize item should have the third index.
<img width="1440" alt="Screenshot 2022-06-14 at 10 46 03" src="https://user-images.githubusercontent.com/66776981/173509974-c615c499-b9ff-4a18-9072-ee30c0df2f55.png">

If the roulette has width 360px your wanted prize item should have the first index.
<img width="1440" alt="Screenshot 2022-06-14 at 10 48 25" src="https://user-images.githubusercontent.com/66776981/173510229-06138247-8d3d-417b-b8cb-5e8f628e3f2b.png">

I hope it will help you but if you have other question just write them here.
