### ISSUE TITLE
How can i set initial index with stopInCenter?

### ISSUE THREAD

**Issue by ngdevc** [IvanAdmaers/react-roulette-pro#8]
![image](https://user-images.githubusercontent.com/65579678/174288105-2592d75d-350a-4ca0-9c0a-c72cc4652887.png)

**Comment by IvanAdmaers** [comment]
You can use the ‘prizeIndex’ prop. There is a live example - https://react-roulette-pro.ivanadmaers.com.

**Comment by ngdevc** [comment]
Yes, i configued it, 
But after roulette moved to the initial Index, the onPrizeDefined is called.
I think it shouldn't be called at the first time.
https://user-images.githubusercontent.com/65579678/174294276-5c7345f0-96cb-4a50-a201-1a6446445e2d.mp4

**Comment by ngdevc** [comment]
@IvanAdmaers

**Comment by IvanAdmaers** [comment]
When your page is loaded your `onPrizeDefined` handler is triggers, right?

**Comment by ngdevc** [comment]
Yes,

**Comment by ngdevc** [comment]
Of course, i can solve it by useState, but too many using of useState reduce the site perfomance. So I don't want to define useState to avoid calling of OnPrizeDefined when the page is loaded.

**Comment by IvanAdmaers** [comment]
I was trying to reproduce it:

```jsx
import React, { useState } from  'react';

import RoulettePro from 'react-roulette-pro';
import 'react-roulette-pro/dist/index.css';

const prizes = [
  {
    id: '7d24b681-82d9-4fc0-b034-c82f9db11a59',
    image: 'https://i.ibb.co/6Z6Xm9d/good-1.png',
  },
  {
    id: '9da9a287-952f-41bd-8c7a-b488938d7c7a',
    image: 'https://i.ibb.co/T1M05LR/good-2.png',
  },
  {
    id: '04106f3f-f99f-47e4-a62e-3c81fc8cf794',
    image: 'https://i.ibb.co/Qbm8cNL/good-3.png',
  },
  {
    id: '23c551bf-8425-4ffd-b7c2-77c87844f89d',
    image: 'https://i.ibb.co/5Tpfs6W/good-4.png',
  },
  {
    id: 'e4060930-538f-4bf7-ab8e-8d2aa05fba43',
    image: 'https://i.ibb.co/64k8D1c/good-5.png',
  },
];

const reproductionArray = (array = [], length = 0) => [
  ...Array(length)
    .fill('_')
    .map(() => array[Math.floor(Math.random() * array.length)]),
];

const prizeList = [
  ...prizes,
  ...reproductionArray(prizes, prizes.length * 3),
  ...prizes,
  ...reproductionArray(prizes, prizes.length),
];

const App = () => {
  const [start, setStart] = useState(false);

  const prizeIndex = prizes.length * 4 + 2;

  const handleStart = () => {
    setStart((prevState) => !prevState);
  };

 
  // It doesn't trigger when the page is loaded
  const handlePrizeDefined = () => {
    console.log('🥳 Prize defined! 🥳');
  };

  return (
    <>
      <RoulettePro
        prizes={prizeList}
        prizeIndex={prizeIndex}
        start={start}
        onPrizeDefined={handlePrizeDefined}
        options={{ stopInCenter: true }}
      />
      <button onClick={handleStart}>Start</button>
    </>
  );
};
```

But this example works correctly. Can you please reproduce this bug and to send an example of the code?

**Comment by ngdevc** [comment]
const RouletteSpinner = ({endRoll}) => {
  const [audio] = useState(new Audio(AudioRolling));
  const [start, setStart] = useState(false);
  const [prizeIndex, setPrizeIndex] = useState(10);
  const { isJoinedRound, isMuted, isRolling } = useContext(AppContext);
  const [isFirstRender, setIsFirstRender] = useState(true);
  const spinning = useMemo(() => isRolling, [isRolling]);

  const handlePrizeDefined = () => {
    if (isFirstRender) setIsFirstRender(false);
    else {
      endRoll({
        index: prizeIndex, 
        color: numberList[prizeIndex].color,
        img: numberList[prizeIndex].img,
        created_at: new Date().toLocaleTimeString()
      });
    }
  };

  useEffect(() => {
    if (prizeIndex && !start) setStart(true);
  }, [prizeIndex, start]);
  
  useEffect(() => {    
    isMuted ? audio.volume = 0 : audio.volume = 1;
  }, [isMuted]) 

  useEffect(() => {
    if (!spinning) return;

    const prepare = async () => {
      const newPrizeIndex = await getPrizeIndex();

      setPrizeIndex(newPrizeIndex);
      setStart(false);
    };

    if (isJoinedRound) audio.play();
    prepare();
  }, [spinning]); 

  return (
    
    <div className={classNames('position-relative', styles.roulette_spinner)}>
      <div className={styles.mask_left}></div>
      <RoulettePro
        design='Regular'
        prizes={numberList}
        prizeIndex={prizeIndex}
        start={start}
        onPrizeDefined={handlePrizeDefined}
        topChildren={<img src={ImgPinTop}/>}
        bottomChildren={<img src={ImgPinBottom}/>}
        options={{stopInCenter: true}}
        designOptions={{
          hideCenterDelimiter: true,
          withoutAnimation: true,
          prizeItemWidth: 70,
        }}
        prizeItemRenderFunction={(props, index) => (
          <li key={props.color + index}>
            <img src={props.img} width='70px'/>
          </li>
        )}
      />
      <div className={styles.mask_right}></div>
    </div>
  )
}

**Comment by ngdevc** [comment]
This is my component,

**Comment by IvanAdmaers** [comment]
Got it.

```jsx
  useEffect(() => {
    if (prizeIndex && !start) setStart(true); // The problem is here
  }, [prizeIndex, start]);
```

Your `prizeIndex` set as `10` by default. So the `useEffect` above changes the `start` prop to true. 

To fix this you should do something like this:
```jsx
const [prizeIndex, setPrizeIndex] = useState(0); // 0 is a falsy value
```

Or

```jsx
const [prizeIndex, setPrizeIndex] = useState(-1);
```

```jsx
  useEffect(() => {
    if (prizeIndex !== -1 && !start) {
      setStart(true);
    }
  }, [prizeIndex, start]);
```

**Comment by ngdevc** [comment]
I got it. I solved it 
thank you.
